### ISSUE TITLE
Недоступны радары по Infrastructure и Backend

### ISSUE THREAD

**Issue by ikurochkin** [dodopizza/RTFM#10]
Привет, у вас не работают технологические радары по Infrastructure и Backend, с остальными проблем нет.
Судя по всему пропал доступ к Google таблицам на основе которых создавался радар.

**Comment by selfdeceited** [comment]
Привет! Я мимо пробегал, вроде уже работают.
Извините, что столько не отвечали :(

Я закрою issue

**Comment by batkaevruslan** [comment]
@selfdeceited , @spacentropy , привет! По инфраструктуре всё ещё не работает ссылка на радар
